name: npm Publish
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    # Publish to npm
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@markbattistella'
    # Publish to GitHub Packages
    - run: npm publish --registry="https://npm.pkg.github.com/@markbattistella"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
